# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='photo',
            field=models.FileField(upload_to='detections'),
        ),
    ]
