# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20171117_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='detections'),
        ),
    ]
